[package]
name = "client-rs"
version = "0.1.0"
authors = ["cpp-baja-sae <rrdscwqumorwekagyl@miucce.online>"]
edition = "2018"

# https://yew.rs/docs/en/getting-started/build-a-sample-app/

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
yew = "0.17"
